

using Bunifu.Framework.UI;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace SignUpDemo
{
  public class Form1 : Form
  {
    private IContainer components = (IContainer) null;
    private Panel panelLeft;
    private Label label1;
    private PictureBox pictureBox1;
    private Panel panelRight;
    private BunifuMaterialTextbox bunifuMaterialTextbox1;
    private Label label3;
    private Label label2;
    private BunifuCheckbox bunifuCheckbox1;
    private Button button1;
    private BunifuMaterialTextbox bunifuMaterialTextbox4;
    private Label label7;
    private Label label6;
    private BunifuMaterialTextbox bunifuMaterialTextbox3;
    private Label label5;
    private BunifuMaterialTextbox bunifuMaterialTextbox2;
    private Label label4;
    private Label label8;
    private BunifuElipse bunifuElipse1;
    private BunifuDragControl bunifuDragControl1;

    public Form1() => this.InitializeComponent();

    private void label8_Click(object sender, EventArgs e) => Application.Exit();

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.components = (IContainer) new System.ComponentModel.Container();
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (Form1));
      this.panelLeft = new Panel();
      this.label1 = new Label();
      this.pictureBox1 = new PictureBox();
      this.panelRight = new Panel();
      this.bunifuCheckbox1 = new BunifuCheckbox();
      this.button1 = new Button();
      this.bunifuMaterialTextbox4 = new BunifuMaterialTextbox();
      this.label7 = new Label();
      this.label6 = new Label();
      this.bunifuMaterialTextbox3 = new BunifuMaterialTextbox();
      this.label5 = new Label();
      this.bunifuMaterialTextbox2 = new BunifuMaterialTextbox();
      this.label4 = new Label();
      this.bunifuMaterialTextbox1 = new BunifuMaterialTextbox();
      this.label3 = new Label();
      this.label8 = new Label();
      this.label2 = new Label();
      this.bunifuElipse1 = new BunifuElipse(this.components);
      this.bunifuDragControl1 = new BunifuDragControl(this.components);
      this.panelLeft.SuspendLayout();
      ((ISupportInitialize) this.pictureBox1).BeginInit();
      this.panelRight.SuspendLayout();
      this.SuspendLayout();
      this.panelLeft.BackColor = Color.FromArgb(238, 26, 74);
      this.panelLeft.Controls.Add((Control) this.label1);
      this.panelLeft.Controls.Add((Control) this.pictureBox1);
      this.panelLeft.Dock = DockStyle.Left;
      this.panelLeft.Location = new Point(0, 0);
      this.panelLeft.Name = "panelLeft";
      this.panelLeft.Size = new Size(321, 543);
      this.panelLeft.TabIndex = 0;
      this.label1.AutoSize = true;
      this.label1.Font = new Font("Century Gothic", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label1.ForeColor = Color.White;
      this.label1.Location = new Point(52, 314);
      this.label1.Name = "label1";
      this.label1.Size = new Size(214, 44);
      this.label1.TabIndex = 1;
      this.label1.Text = "We Create, We Design\r\n       We Develop";
      this.pictureBox1.Image = (Image) componentResourceManager.GetObject("pictureBox1.Image");
      this.pictureBox1.Location = new Point(66, 103);
      this.pictureBox1.Name = "pictureBox1";
      this.pictureBox1.Size = new Size(190, 196);
      this.pictureBox1.SizeMode = PictureBoxSizeMode.Zoom;
      this.pictureBox1.TabIndex = 0;
      this.pictureBox1.TabStop = false;
      this.panelRight.Controls.Add((Control) this.bunifuCheckbox1);
      this.panelRight.Controls.Add((Control) this.button1);
      this.panelRight.Controls.Add((Control) this.bunifuMaterialTextbox4);
      this.panelRight.Controls.Add((Control) this.label7);
      this.panelRight.Controls.Add((Control) this.label6);
      this.panelRight.Controls.Add((Control) this.bunifuMaterialTextbox3);
      this.panelRight.Controls.Add((Control) this.label5);
      this.panelRight.Controls.Add((Control) this.bunifuMaterialTextbox2);
      this.panelRight.Controls.Add((Control) this.label4);
      this.panelRight.Controls.Add((Control) this.bunifuMaterialTextbox1);
      this.panelRight.Controls.Add((Control) this.label3);
      this.panelRight.Controls.Add((Control) this.label8);
      this.panelRight.Controls.Add((Control) this.label2);
      this.panelRight.Dock = DockStyle.Fill;
      this.panelRight.Location = new Point(321, 0);
      this.panelRight.Name = "panelRight";
      this.panelRight.Size = new Size(344, 543);
      this.panelRight.TabIndex = 1;
      this.bunifuCheckbox1.BackColor = Color.FromArgb(238, 26, 74);
      this.bunifuCheckbox1.ChechedOffColor = Color.FromArgb(132, 135, 140);
      this.bunifuCheckbox1.Checked = true;
      this.bunifuCheckbox1.CheckedOnColor = Color.FromArgb(238, 26, 74);
      this.bunifuCheckbox1.ForeColor = Color.White;
      this.bunifuCheckbox1.Location = new Point(40, 396);
      this.bunifuCheckbox1.Name = "bunifuCheckbox1";
      this.bunifuCheckbox1.Size = new Size(20, 20);
      this.bunifuCheckbox1.TabIndex = 3;
      this.button1.BackColor = Color.FromArgb(238, 26, 74);
      this.button1.FlatStyle = FlatStyle.Flat;
      this.button1.Font = new Font("Century Gothic", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.button1.ForeColor = Color.White;
      this.button1.Location = new Point(21, 444);
      this.button1.Name = "button1";
      this.button1.Size = new Size(297, 34);
      this.button1.TabIndex = 2;
      this.button1.Text = "Sign Up";
      this.button1.UseVisualStyleBackColor = false;
      this.bunifuMaterialTextbox4.Cursor = Cursors.IBeam;
      this.bunifuMaterialTextbox4.Font = new Font("Century Gothic", 9.75f);
      this.bunifuMaterialTextbox4.ForeColor = Color.FromArgb(64, 64, 64);
      this.bunifuMaterialTextbox4.HintForeColor = Color.Empty;
      this.bunifuMaterialTextbox4.HintText = "someone@example.com";
      this.bunifuMaterialTextbox4.isPassword = false;
      this.bunifuMaterialTextbox4.LineFocusedColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox4.LineIdleColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox4.LineMouseHoverColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox4.LineThickness = 3;
      this.bunifuMaterialTextbox4.Location = new Point(21, 341);
      this.bunifuMaterialTextbox4.Margin = new Padding(4);
      this.bunifuMaterialTextbox4.Name = "bunifuMaterialTextbox4";
      this.bunifuMaterialTextbox4.Size = new Size(297, 31);
      this.bunifuMaterialTextbox4.TabIndex = 1;
      this.bunifuMaterialTextbox4.TextAlign = HorizontalAlignment.Left;
      this.label7.AutoSize = true;
      this.label7.Font = new Font("Century Gothic", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label7.ForeColor = Color.FromArgb(238, 26, 74);
      this.label7.Location = new Point(66, 395);
      this.label7.Name = "label7";
      this.label7.Size = new Size(239, 21);
      this.label7.TabIndex = 0;
      this.label7.Text = "I Agree Terms and Conditions";
      this.label6.AutoSize = true;
      this.label6.Font = new Font("Century Gothic", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label6.ForeColor = Color.FromArgb(238, 26, 74);
      this.label6.Location = new Point(17, 324);
      this.label6.Name = "label6";
      this.label6.Size = new Size(55, 21);
      this.label6.TabIndex = 0;
      this.label6.Text = "Email:";
      this.bunifuMaterialTextbox3.Cursor = Cursors.IBeam;
      this.bunifuMaterialTextbox3.Font = new Font("Century Gothic", 9.75f);
      this.bunifuMaterialTextbox3.ForeColor = Color.FromArgb(64, 64, 64);
      this.bunifuMaterialTextbox3.HintForeColor = Color.Empty;
      this.bunifuMaterialTextbox3.HintText = "";
      this.bunifuMaterialTextbox3.isPassword = true;
      this.bunifuMaterialTextbox3.LineFocusedColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox3.LineIdleColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox3.LineMouseHoverColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox3.LineThickness = 3;
      this.bunifuMaterialTextbox3.Location = new Point(21, 270);
      this.bunifuMaterialTextbox3.Margin = new Padding(4);
      this.bunifuMaterialTextbox3.Name = "bunifuMaterialTextbox3";
      this.bunifuMaterialTextbox3.Size = new Size(297, 31);
      this.bunifuMaterialTextbox3.TabIndex = 1;
      this.bunifuMaterialTextbox3.Text = "Password";
      this.bunifuMaterialTextbox3.TextAlign = HorizontalAlignment.Left;
      this.label5.AutoSize = true;
      this.label5.Font = new Font("Century Gothic", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label5.ForeColor = Color.FromArgb(238, 26, 74);
      this.label5.Location = new Point(17, 253);
      this.label5.Name = "label5";
      this.label5.Size = new Size(156, 21);
      this.label5.TabIndex = 0;
      this.label5.Text = "Re-Enter Password:";
      this.bunifuMaterialTextbox2.Cursor = Cursors.IBeam;
      this.bunifuMaterialTextbox2.Font = new Font("Century Gothic", 9.75f);
      this.bunifuMaterialTextbox2.ForeColor = Color.FromArgb(64, 64, 64);
      this.bunifuMaterialTextbox2.HintForeColor = Color.Empty;
      this.bunifuMaterialTextbox2.HintText = "";
      this.bunifuMaterialTextbox2.isPassword = true;
      this.bunifuMaterialTextbox2.LineFocusedColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox2.LineIdleColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox2.LineMouseHoverColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox2.LineThickness = 3;
      this.bunifuMaterialTextbox2.Location = new Point(21, 199);
      this.bunifuMaterialTextbox2.Margin = new Padding(4);
      this.bunifuMaterialTextbox2.Name = "bunifuMaterialTextbox2";
      this.bunifuMaterialTextbox2.Size = new Size(297, 31);
      this.bunifuMaterialTextbox2.TabIndex = 1;
      this.bunifuMaterialTextbox2.Text = "Password";
      this.bunifuMaterialTextbox2.TextAlign = HorizontalAlignment.Left;
      this.label4.AutoSize = true;
      this.label4.Font = new Font("Century Gothic", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label4.ForeColor = Color.FromArgb(238, 26, 74);
      this.label4.Location = new Point(17, 182);
      this.label4.Name = "label4";
      this.label4.Size = new Size(86, 21);
      this.label4.TabIndex = 0;
      this.label4.Text = "Password:";
      this.bunifuMaterialTextbox1.Cursor = Cursors.IBeam;
      this.bunifuMaterialTextbox1.Font = new Font("Century Gothic", 9.75f);
      this.bunifuMaterialTextbox1.ForeColor = Color.FromArgb(64, 64, 64);
      this.bunifuMaterialTextbox1.HintForeColor = Color.Empty;
      this.bunifuMaterialTextbox1.HintText = "Full Name";
      this.bunifuMaterialTextbox1.isPassword = false;
      this.bunifuMaterialTextbox1.LineFocusedColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox1.LineIdleColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox1.LineMouseHoverColor = Color.FromArgb(238, 26, 74);
      this.bunifuMaterialTextbox1.LineThickness = 3;
      this.bunifuMaterialTextbox1.Location = new Point(21, 136);
      this.bunifuMaterialTextbox1.Margin = new Padding(4);
      this.bunifuMaterialTextbox1.Name = "bunifuMaterialTextbox1";
      this.bunifuMaterialTextbox1.Size = new Size(297, 31);
      this.bunifuMaterialTextbox1.TabIndex = 1;
      this.bunifuMaterialTextbox1.TextAlign = HorizontalAlignment.Left;
      this.label3.AutoSize = true;
      this.label3.Font = new Font("Century Gothic", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label3.ForeColor = Color.FromArgb(238, 26, 74);
      this.label3.Location = new Point(17, 111);
      this.label3.Name = "label3";
      this.label3.Size = new Size(98, 21);
      this.label3.TabIndex = 0;
      this.label3.Text = "User Name:";
      this.label8.AutoSize = true;
      this.label8.Font = new Font("Century Gothic", 18f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label8.ForeColor = Color.FromArgb(238, 26, 74);
      this.label8.Location = new Point(309, 2);
      this.label8.Name = "label8";
      this.label8.Size = new Size(25, 30);
      this.label8.TabIndex = 0;
      this.label8.Text = "x";
      this.label8.Click += new EventHandler(this.label8_Click);
      this.label2.AutoSize = true;
      this.label2.Font = new Font("Century Gothic", 18f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label2.ForeColor = Color.FromArgb(238, 26, 74);
      this.label2.Location = new Point(16, 57);
      this.label2.Name = "label2";
      this.label2.Size = new Size(101, 30);
      this.label2.TabIndex = 0;
      this.label2.Text = "Sign Up";
      this.bunifuElipse1.ElipseRadius = 25;
      this.bunifuElipse1.TargetControl = (Control) this;
      this.bunifuDragControl1.Fixed = true;
      this.bunifuDragControl1.Horizontal = true;
      this.bunifuDragControl1.TargetControl = (Control) this.panelLeft;
      this.bunifuDragControl1.Vertical = true;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(665, 543);
      this.Controls.Add((Control) this.panelRight);
      this.Controls.Add((Control) this.panelLeft);
      this.FormBorderStyle = FormBorderStyle.None;
      this.Name = nameof (Form1);
      this.StartPosition = FormStartPosition.CenterScreen;
      this.Text = nameof (Form1);
      this.panelLeft.ResumeLayout(false);
      this.panelLeft.PerformLayout();
      ((ISupportInitialize) this.pictureBox1).EndInit();
      this.panelRight.ResumeLayout(false);
      this.panelRight.PerformLayout();
      this.ResumeLayout(false);
    }
  }
}
