
using CustomDataGridViewNamespace;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace PawnManagement.JewelleryForms
{
  public class FormOldPurchase : Form
  {
    private IContainer components = (IContainer) null;
    private Label label1;
    private CustomDataGridView dgvPureWeightCalculator;
    private CustomDataGridView customDataGridView2;
    private DataGridViewTextBoxColumn colSerialTotal;
    private DataGridViewComboBoxColumn colPurityTotal;
    private DataGridViewTextBoxColumn colWeightTotal;
    private DataGridViewTextBoxColumn colPureWeightTotal;
    private DataGridViewTextBoxColumn colRowNumber;
    private DataGridViewTextBoxColumn colComapnyCode;
    private DataGridViewTextBoxColumn colSerialNumber;
    private DataGridViewTextBoxColumn colBillNumber;
    private DataGridViewTextBoxColumn colBillDate;
    private DataGridViewTextBoxColumn colCustomerCode;
    private DataGridViewTextBoxColumn colMetal;
    private DataGridViewTextBoxColumn colItemname;
    private DataGridViewTextBoxColumn colDescription;
    private DataGridViewTextBoxColumn colGrossWeight;
    private DataGridViewTextBoxColumn colDirt;
    private DataGridViewTextBoxColumn colArakku;
    private DataGridViewTextBoxColumn colStoneOrEnamel;
    private DataGridViewTextBoxColumn colNetWeigh;
    private DataGridViewTextBoxColumn colPurity;
    private DataGridViewTextBoxColumn colPureWeight;
    private DataGridViewTextBoxColumn colRate;
    private DataGridViewTextBoxColumn colAmount;

    public FormOldPurchase() => this.InitializeComponent();

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      DataGridViewCellStyle gridViewCellStyle1 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle2 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle3 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle4 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle5 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle6 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle7 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle8 = new DataGridViewCellStyle();
      this.label1 = new Label();
      this.dgvPureWeightCalculator = new CustomDataGridView();
      this.customDataGridView2 = new CustomDataGridView();
      this.colSerialTotal = new DataGridViewTextBoxColumn();
      this.colPurityTotal = new DataGridViewComboBoxColumn();
      this.colWeightTotal = new DataGridViewTextBoxColumn();
      this.colPureWeightTotal = new DataGridViewTextBoxColumn();
      this.colRowNumber = new DataGridViewTextBoxColumn();
      this.colComapnyCode = new DataGridViewTextBoxColumn();
      this.colSerialNumber = new DataGridViewTextBoxColumn();
      this.colBillNumber = new DataGridViewTextBoxColumn();
      this.colBillDate = new DataGridViewTextBoxColumn();
      this.colCustomerCode = new DataGridViewTextBoxColumn();
      this.colMetal = new DataGridViewTextBoxColumn();
      this.colItemname = new DataGridViewTextBoxColumn();
      this.colDescription = new DataGridViewTextBoxColumn();
      this.colGrossWeight = new DataGridViewTextBoxColumn();
      this.colDirt = new DataGridViewTextBoxColumn();
      this.colArakku = new DataGridViewTextBoxColumn();
      this.colStoneOrEnamel = new DataGridViewTextBoxColumn();
      this.colNetWeigh = new DataGridViewTextBoxColumn();
      this.colPurity = new DataGridViewTextBoxColumn();
      this.colPureWeight = new DataGridViewTextBoxColumn();
      this.colRate = new DataGridViewTextBoxColumn();
      this.colAmount = new DataGridViewTextBoxColumn();
      ((ISupportInitialize) this.dgvPureWeightCalculator).BeginInit();
      ((ISupportInitialize) this.customDataGridView2).BeginInit();
      this.SuspendLayout();
      this.label1.AutoSize = true;
      this.label1.Font = new Font("Microsoft Sans Serif", 20.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label1.ForeColor = Color.White;
      this.label1.Location = new Point(398, 5);
      this.label1.Name = "label1";
      this.label1.Size = new Size(229, 31);
      this.label1.TabIndex = 5;
      this.label1.Text = "OLD PURCHASE";
      ((DataGridView) this.dgvPureWeightCalculator).AllowUserToAddRows = false;
      ((DataGridView) this.dgvPureWeightCalculator).AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
      ((DataGridView) this.dgvPureWeightCalculator).BorderStyle = BorderStyle.None;
      ((DataGridView) this.dgvPureWeightCalculator).ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.Single;
      gridViewCellStyle1.Alignment = DataGridViewContentAlignment.MiddleCenter;
      gridViewCellStyle1.BackColor = SystemColors.ControlDark;
      gridViewCellStyle1.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle1.ForeColor = SystemColors.WindowText;
      gridViewCellStyle1.SelectionBackColor = SystemColors.Highlight;
      gridViewCellStyle1.SelectionForeColor = SystemColors.HighlightText;
      gridViewCellStyle1.WrapMode = DataGridViewTriState.True;
      ((DataGridView) this.dgvPureWeightCalculator).ColumnHeadersDefaultCellStyle = gridViewCellStyle1;
      ((DataGridView) this.dgvPureWeightCalculator).ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      ((DataGridView) this.dgvPureWeightCalculator).Columns.AddRange((DataGridViewColumn) this.colRowNumber, (DataGridViewColumn) this.colComapnyCode, (DataGridViewColumn) this.colSerialNumber, (DataGridViewColumn) this.colBillNumber, (DataGridViewColumn) this.colBillDate, (DataGridViewColumn) this.colCustomerCode, (DataGridViewColumn) this.colMetal, (DataGridViewColumn) this.colItemname, (DataGridViewColumn) this.colDescription, (DataGridViewColumn) this.colGrossWeight, (DataGridViewColumn) this.colDirt, (DataGridViewColumn) this.colArakku, (DataGridViewColumn) this.colStoneOrEnamel, (DataGridViewColumn) this.colNetWeigh, (DataGridViewColumn) this.colPurity, (DataGridViewColumn) this.colPureWeight, (DataGridViewColumn) this.colRate, (DataGridViewColumn) this.colAmount);
      gridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
      gridViewCellStyle2.BackColor = SystemColors.Window;
      gridViewCellStyle2.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle2.ForeColor = SystemColors.ControlText;
      gridViewCellStyle2.SelectionBackColor = SystemColors.Highlight;
      gridViewCellStyle2.SelectionForeColor = SystemColors.HighlightText;
      gridViewCellStyle2.WrapMode = DataGridViewTriState.False;
      ((DataGridView) this.dgvPureWeightCalculator).DefaultCellStyle = gridViewCellStyle2;
      ((DataGridView) this.dgvPureWeightCalculator).EditMode = DataGridViewEditMode.EditOnEnter;
      ((DataGridView) this.dgvPureWeightCalculator).GridColor = SystemColors.Control;
      ((Control) this.dgvPureWeightCalculator).Location = new Point(5, 43);
      ((Control) this.dgvPureWeightCalculator).Name = "dgvPureWeightCalculator";
      ((DataGridView) this.dgvPureWeightCalculator).RowHeadersVisible = false;
      ((Control) this.dgvPureWeightCalculator).Size = new Size(1008, 347);
      ((Control) this.dgvPureWeightCalculator).TabIndex = 3;
      ((DataGridView) this.customDataGridView2).AllowUserToAddRows = false;
      ((DataGridView) this.customDataGridView2).AllowUserToDeleteRows = false;
      ((Control) this.customDataGridView2).Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
      ((DataGridView) this.customDataGridView2).AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
      ((DataGridView) this.customDataGridView2).BackgroundColor = SystemColors.Control;
      ((DataGridView) this.customDataGridView2).BorderStyle = BorderStyle.None;
      ((DataGridView) this.customDataGridView2).ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
      ((DataGridView) this.customDataGridView2).ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
      ((DataGridView) this.customDataGridView2).ColumnHeadersVisible = false;
      ((DataGridView) this.customDataGridView2).Columns.AddRange((DataGridViewColumn) this.colSerialTotal, (DataGridViewColumn) this.colPurityTotal, (DataGridViewColumn) this.colWeightTotal, (DataGridViewColumn) this.colPureWeightTotal);
      gridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
      gridViewCellStyle3.BackColor = SystemColors.Window;
      gridViewCellStyle3.Font = new Font("Microsoft Sans Serif", 26.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle3.ForeColor = SystemColors.ControlText;
      gridViewCellStyle3.SelectionBackColor = SystemColors.ControlLightLight;
      gridViewCellStyle3.SelectionForeColor = SystemColors.Desktop;
      gridViewCellStyle3.WrapMode = DataGridViewTriState.False;
      ((DataGridView) this.customDataGridView2).DefaultCellStyle = gridViewCellStyle3;
      ((DataGridView) this.customDataGridView2).EditMode = DataGridViewEditMode.EditOnEnter;
      ((Control) this.customDataGridView2).Location = new Point(5, 387);
      ((Control) this.customDataGridView2).Name = "customDataGridView2";
      ((DataGridView) this.customDataGridView2).ReadOnly = true;
      ((DataGridView) this.customDataGridView2).RowHeadersVisible = false;
      ((DataGridView) this.customDataGridView2).RowTemplate.DefaultCellStyle.Font = new Font("Microsoft Sans Serif", 26.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      ((DataGridView) this.customDataGridView2).RowTemplate.Height = 35;
      ((DataGridView) this.customDataGridView2).SelectionMode = DataGridViewSelectionMode.FullRowSelect;
      ((Control) this.customDataGridView2).Size = new Size(1008, 40);
      ((Control) this.customDataGridView2).TabIndex = 4;
      gridViewCellStyle4.Alignment = DataGridViewContentAlignment.MiddleCenter;
      this.colSerialTotal.DefaultCellStyle = gridViewCellStyle4;
      this.colSerialTotal.FillWeight = 20f;
      this.colSerialTotal.HeaderText = "Sl.No";
      this.colSerialTotal.Name = "colSerialTotal";
      this.colSerialTotal.ReadOnly = true;
      gridViewCellStyle5.Alignment = DataGridViewContentAlignment.MiddleLeft;
      this.colPurityTotal.DefaultCellStyle = gridViewCellStyle5;
      this.colPurityTotal.DisplayStyle = DataGridViewComboBoxDisplayStyle.Nothing;
      this.colPurityTotal.FillWeight = 20f;
      this.colPurityTotal.FlatStyle = FlatStyle.Flat;
      this.colPurityTotal.HeaderText = "Type";
      this.colPurityTotal.Items.AddRange((object) "1.BILL", (object) "2.JAMMA", (object) "3.KACHA", (object) "4.CHEQUE", (object) "5.KACHA RETURN", (object) "6.TAX", (object) "7.BYAAJ");
      this.colPurityTotal.Name = "colPurityTotal";
      this.colPurityTotal.ReadOnly = true;
      this.colPurityTotal.Resizable = DataGridViewTriState.True;
      this.colPurityTotal.SortMode = DataGridViewColumnSortMode.Automatic;
      gridViewCellStyle6.Alignment = DataGridViewContentAlignment.MiddleRight;
      this.colWeightTotal.DefaultCellStyle = gridViewCellStyle6;
      this.colWeightTotal.FillWeight = 30f;
      this.colWeightTotal.HeaderText = "Amount";
      this.colWeightTotal.Name = "colWeightTotal";
      this.colWeightTotal.ReadOnly = true;
      gridViewCellStyle7.Alignment = DataGridViewContentAlignment.MiddleRight;
      this.colPureWeightTotal.DefaultCellStyle = gridViewCellStyle7;
      this.colPureWeightTotal.FillWeight = 30f;
      this.colPureWeightTotal.HeaderText = "CD";
      this.colPureWeightTotal.Name = "colPureWeightTotal";
      this.colPureWeightTotal.ReadOnly = true;
      gridViewCellStyle8.Alignment = DataGridViewContentAlignment.MiddleCenter;
      this.colRowNumber.DefaultCellStyle = gridViewCellStyle8;
      this.colRowNumber.FillWeight = 20f;
      this.colRowNumber.HeaderText = "SLNO";
      this.colRowNumber.Name = "colRowNumber";
      this.colComapnyCode.HeaderText = "COMPANY CODE";
      this.colComapnyCode.Name = "colComapnyCode";
      this.colSerialNumber.HeaderText = "SL No";
      this.colSerialNumber.Name = "colSerialNumber";
      this.colBillNumber.HeaderText = "BILL NUMBER";
      this.colBillNumber.Name = "colBillNumber";
      this.colBillDate.HeaderText = "BILLDATE";
      this.colBillDate.Name = "colBillDate";
      this.colCustomerCode.HeaderText = "CUSTOMERCODE";
      this.colCustomerCode.Name = "colCustomerCode";
      this.colMetal.HeaderText = "METAL";
      this.colMetal.Name = "colMetal";
      this.colItemname.HeaderText = "ITEMNAME";
      this.colItemname.Name = "colItemname";
      this.colDescription.HeaderText = "DESCRIPTION";
      this.colDescription.Name = "colDescription";
      this.colGrossWeight.HeaderText = "GROSSWEIGHT";
      this.colGrossWeight.Name = "colGrossWeight";
      this.colDirt.HeaderText = "DIRT";
      this.colDirt.Name = "colDirt";
      this.colArakku.HeaderText = "ARAKKU";
      this.colArakku.Name = "colArakku";
      this.colStoneOrEnamel.HeaderText = "STONE/ENAMEL";
      this.colStoneOrEnamel.Name = "colStoneOrEnamel";
      this.colNetWeigh.HeaderText = "NETWEIGHT";
      this.colNetWeigh.Name = "colNetWeigh";
      this.colPurity.HeaderText = "PURITY";
      this.colPurity.Name = "colPurity";
      this.colPureWeight.HeaderText = "PUREWEIGHT";
      this.colPureWeight.Name = "colPureWeight";
      this.colRate.HeaderText = "RATE";
      this.colRate.Name = "colRate";
      this.colAmount.HeaderText = "AMOUNT";
      this.colAmount.Name = "colAmount";
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.BackColor = Color.DimGray;
      this.ClientSize = new Size(1024, 429);
      this.Controls.Add((Control) this.label1);
      this.Controls.Add((Control) this.dgvPureWeightCalculator);
      this.Controls.Add((Control) this.customDataGridView2);
      this.FormBorderStyle = FormBorderStyle.None;
      this.Name = nameof (FormOldPurchase);
      this.Text = nameof (FormOldPurchase);
      ((ISupportInitialize) this.dgvPureWeightCalculator).EndInit();
      ((ISupportInitialize) this.customDataGridView2).EndInit();
      this.ResumeLayout(false);
      this.PerformLayout();
    }
  }
}
