

using Glass;
using KIS.Controls;
using KIS.Controls.Windows;
using PawnManagement.Properties;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;
using ZeeUIUtility;

namespace PawnManagement.Forms
{
  public class FormPledgeBill : Form
  {
    private string BillNumber = "";
    private IContainer components = (IContainer) null;
    private TextBox textBox13;
    private TextBox tbxPureWeight;
    private TextBox textBox12;
    private TextBox textBox11;
    private TextBox textBox10;
    private TextBox textBox9;
    private TextBox textBox8;
    private TextBox textBox7;
    private TextBox tbxReminder;
    private TextBox textBox6;
    private TextBox tbxOldBillNumber;
    private TextBox tbxDeductions;
    private TextBox textBox5;
    private ComboBox cbType;
    private TextBox textBox4;
    private TextBox textBox3;
    private TextBox tbxweight;
    private TextBox textBox2;
    private TextBox textBox1;
    private TextBox tbxPay;
    private DataGridViewEx dgvArticles;
    private ContextMenuStrip contextMenuStrip1;
    private ToolStripMenuItem deleteToolStripMenuItem;
    private Panel panel5;
    private TextBox tbxTotalInterest;
    private TextBox tbxChit;
    private TextBox tbxNetWeight;
    private TextBox tbxInteresRate;
    private TextBox tbxAmount;
    private TextBox tbxValue;
    private HeaderPanel headerPanel2;
    private TextBox tbxAverageNumberOfDaysForRelease;
    private TextBox tbxNumberOfTimesReleaseExceedTwelveMonths;
    private TextBox tbxCustomerName;
    private TextBox tbxCustomerCode;
    private TextBox tbxPhoneNumber;
    private TextBox tbxAddress3;
    private TextBox tbxCell;
    private TextBox tbxPincode;
    private TextBox tbxAddress1;
    private TextBox tbxCity;
    private TextBox tbxAddress2;
    private HeaderPanel headerPanel1;
    private DataGridViewComboBoxColumn colArticles;
    private GlassButton btnEdit;
    private TextBox tbxNotes;
    private Panel panel3;
    private TextBox tbxNumber;
    private PictureBox pictureBox2;
    private ContextMenuStrip contextMenuStrip2;
    private ToolStripMenuItem exportToExcelToolStripMenuItem;
    private ToolStripMenuItem wrapToolStripMenuItem;
    private ToolStripMenuItem viewFullScreenToolStripMenuItem;
    private Panel panel1;
    private HeaderPanel headerPanel6;
    private GlassButton glassButton3;
    private GlassButton glassButton4;
    private TextBox tbxBillDate;
    private HeaderPanel headerPanel5;
    private GlassButton glassButton1;
    private GlassButton glassButton2;
    private TextBox tbxBillNumber;
    private HeaderPanel headerPanel7;
    private ComboBox cbShopCodes;
    private GlassButton glassButton8;
    private GlassButton glassButton9;
    private HeaderPanel headerPanel3;
    private TableLayoutPanel tableLayoutPanel2;
    private Timer timer1;
    private DataGridViewTextBoxColumn colPureWeight;
    private DataGridViewTextBoxColumn colHiddenRemarks;
    private DataGridViewTextBoxColumn colPurity;
    private DataGridViewTextBoxColumn colNetWeight;
    private DataGridViewTextBoxColumn colDeduction;
    private DataGridViewTextBoxColumn colGrossWeight;
    private DataGridViewTextBoxColumn colNo;
    private DataGridViewTextBoxColumn colArticlesDetails;

    public FormPledgeBill(string BILLNUMBER)
    {
      this.BillNumber = BILLNUMBER;
      this.InitializeComponent();
    }

    private void FormPledgeBill_Load(object sender, EventArgs e)
    {
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.components = (IContainer) new System.ComponentModel.Container();
      DataGridViewCellStyle gridViewCellStyle1 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle2 = new DataGridViewCellStyle();
      this.textBox13 = new TextBox();
      this.tbxPureWeight = new TextBox();
      this.textBox12 = new TextBox();
      this.textBox11 = new TextBox();
      this.textBox10 = new TextBox();
      this.textBox9 = new TextBox();
      this.textBox8 = new TextBox();
      this.textBox7 = new TextBox();
      this.tbxReminder = new TextBox();
      this.textBox6 = new TextBox();
      this.tbxOldBillNumber = new TextBox();
      this.tbxDeductions = new TextBox();
      this.textBox5 = new TextBox();
      this.cbType = new ComboBox();
      this.textBox4 = new TextBox();
      this.textBox3 = new TextBox();
      this.tbxweight = new TextBox();
      this.textBox2 = new TextBox();
      this.textBox1 = new TextBox();
      this.tbxPay = new TextBox();
      this.dgvArticles = new DataGridViewEx();
      this.contextMenuStrip1 = new ContextMenuStrip(this.components);
      this.deleteToolStripMenuItem = new ToolStripMenuItem();
      this.panel5 = new Panel();
      this.tbxTotalInterest = new TextBox();
      this.tbxChit = new TextBox();
      this.tbxNetWeight = new TextBox();
      this.tbxInteresRate = new TextBox();
      this.tbxAmount = new TextBox();
      this.tbxValue = new TextBox();
      this.headerPanel2 = new HeaderPanel();
      this.tbxAverageNumberOfDaysForRelease = new TextBox();
      this.tbxNumberOfTimesReleaseExceedTwelveMonths = new TextBox();
      this.tbxCustomerName = new TextBox();
      this.tbxCustomerCode = new TextBox();
      this.tbxPhoneNumber = new TextBox();
      this.tbxAddress3 = new TextBox();
      this.tbxCell = new TextBox();
      this.tbxPincode = new TextBox();
      this.tbxAddress1 = new TextBox();
      this.tbxCity = new TextBox();
      this.tbxAddress2 = new TextBox();
      this.headerPanel1 = new HeaderPanel();
      this.colArticles = new DataGridViewComboBoxColumn();
      this.btnEdit = new GlassButton();
      this.tbxNotes = new TextBox();
      this.panel3 = new Panel();
      this.tbxNumber = new TextBox();
      this.pictureBox2 = new PictureBox();
      this.contextMenuStrip2 = new ContextMenuStrip(this.components);
      this.exportToExcelToolStripMenuItem = new ToolStripMenuItem();
      this.wrapToolStripMenuItem = new ToolStripMenuItem();
      this.viewFullScreenToolStripMenuItem = new ToolStripMenuItem();
      this.panel1 = new Panel();
      this.headerPanel6 = new HeaderPanel();
      this.glassButton3 = new GlassButton();
      this.glassButton4 = new GlassButton();
      this.tbxBillDate = new TextBox();
      this.headerPanel5 = new HeaderPanel();
      this.glassButton1 = new GlassButton();
      this.glassButton2 = new GlassButton();
      this.tbxBillNumber = new TextBox();
      this.headerPanel7 = new HeaderPanel();
      this.cbShopCodes = new ComboBox();
      this.glassButton8 = new GlassButton();
      this.glassButton9 = new GlassButton();
      this.headerPanel3 = new HeaderPanel();
      this.tableLayoutPanel2 = new TableLayoutPanel();
      this.timer1 = new Timer(this.components);
      this.colPureWeight = new DataGridViewTextBoxColumn();
      this.colHiddenRemarks = new DataGridViewTextBoxColumn();
      this.colPurity = new DataGridViewTextBoxColumn();
      this.colNetWeight = new DataGridViewTextBoxColumn();
      this.colDeduction = new DataGridViewTextBoxColumn();
      this.colGrossWeight = new DataGridViewTextBoxColumn();
      this.colNo = new DataGridViewTextBoxColumn();
      this.colArticlesDetails = new DataGridViewTextBoxColumn();
      ((ISupportInitialize) this.dgvArticles).BeginInit();
      this.contextMenuStrip1.SuspendLayout();
      this.panel5.SuspendLayout();
      ((Control) this.headerPanel1).SuspendLayout();
      this.panel3.SuspendLayout();
      ((ISupportInitialize) this.pictureBox2).BeginInit();
      this.contextMenuStrip2.SuspendLayout();
      this.panel1.SuspendLayout();
      ((Control) this.headerPanel6).SuspendLayout();
      ((Control) this.headerPanel5).SuspendLayout();
      ((Control) this.headerPanel7).SuspendLayout();
      ((Control) this.headerPanel3).SuspendLayout();
      this.tableLayoutPanel2.SuspendLayout();
      this.SuspendLayout();
      this.textBox13.Anchor = AnchorStyles.None;
      this.textBox13.BackColor = Color.AliceBlue;
      this.textBox13.BorderStyle = BorderStyle.None;
      this.textBox13.CharacterCasing = CharacterCasing.Upper;
      this.textBox13.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox13.ForeColor = Color.DarkBlue;
      this.textBox13.Location = new Point(13, 265);
      this.textBox13.MaxLength = 4;
      this.textBox13.Name = "textBox13";
      this.textBox13.Size = new Size(114, 22);
      this.textBox13.TabIndex = 70;
      this.textBox13.Text = "PURE WT";
      this.textBox13.TextAlign = HorizontalAlignment.Right;
      this.tbxPureWeight.Anchor = AnchorStyles.None;
      this.tbxPureWeight.BorderStyle = BorderStyle.FixedSingle;
      this.tbxPureWeight.CharacterCasing = CharacterCasing.Upper;
      this.tbxPureWeight.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxPureWeight.Location = new Point(144, 262);
      this.tbxPureWeight.MaxLength = 7;
      this.tbxPureWeight.Name = "tbxPureWeight";
      this.tbxPureWeight.ReadOnly = true;
      this.tbxPureWeight.Size = new Size(145, 29);
      this.tbxPureWeight.TabIndex = 69;
      this.tbxPureWeight.TextAlign = HorizontalAlignment.Right;
      this.textBox12.Anchor = AnchorStyles.None;
      this.textBox12.BackColor = Color.AliceBlue;
      this.textBox12.BorderStyle = BorderStyle.None;
      this.textBox12.CharacterCasing = CharacterCasing.Upper;
      this.textBox12.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox12.ForeColor = Color.DarkBlue;
      this.textBox12.Location = new Point(27, 55);
      this.textBox12.MaxLength = 4;
      this.textBox12.Name = "textBox12";
      this.textBox12.Size = new Size(114, 22);
      this.textBox12.TabIndex = 67;
      this.textBox12.Text = "TYPE   ";
      this.textBox12.TextAlign = HorizontalAlignment.Right;
      this.textBox11.Anchor = AnchorStyles.None;
      this.textBox11.BackColor = Color.AliceBlue;
      this.textBox11.BorderStyle = BorderStyle.None;
      this.textBox11.CharacterCasing = CharacterCasing.Upper;
      this.textBox11.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox11.ForeColor = Color.DarkBlue;
      this.textBox11.Location = new Point(24, 92);
      this.textBox11.MaxLength = 4;
      this.textBox11.Name = "textBox11";
      this.textBox11.Size = new Size(114, 22);
      this.textBox11.TabIndex = 66;
      this.textBox11.Text = "OLD NO   ";
      this.textBox11.TextAlign = HorizontalAlignment.Right;
      this.textBox10.Anchor = AnchorStyles.None;
      this.textBox10.BackColor = Color.AliceBlue;
      this.textBox10.BorderStyle = BorderStyle.None;
      this.textBox10.CharacterCasing = CharacterCasing.Upper;
      this.textBox10.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox10.ForeColor = Color.DarkBlue;
      this.textBox10.Location = new Point(27, 128);
      this.textBox10.MaxLength = 4;
      this.textBox10.Name = "textBox10";
      this.textBox10.Size = new Size(114, 22);
      this.textBox10.TabIndex = 65;
      this.textBox10.Text = "REMINDER   ";
      this.textBox10.TextAlign = HorizontalAlignment.Right;
      this.textBox9.Anchor = AnchorStyles.None;
      this.textBox9.BackColor = Color.AliceBlue;
      this.textBox9.BorderStyle = BorderStyle.None;
      this.textBox9.CharacterCasing = CharacterCasing.Upper;
      this.textBox9.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox9.ForeColor = Color.DarkBlue;
      this.textBox9.Location = new Point(27, 164);
      this.textBox9.MaxLength = 4;
      this.textBox9.Name = "textBox9";
      this.textBox9.Size = new Size(114, 22);
      this.textBox9.TabIndex = 64;
      this.textBox9.Text = "GROSS WT   ";
      this.textBox9.TextAlign = HorizontalAlignment.Right;
      this.textBox8.Anchor = AnchorStyles.None;
      this.textBox8.BackColor = Color.AliceBlue;
      this.textBox8.BorderStyle = BorderStyle.None;
      this.textBox8.CharacterCasing = CharacterCasing.Upper;
      this.textBox8.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox8.ForeColor = Color.DarkBlue;
      this.textBox8.Location = new Point(19, 199);
      this.textBox8.MaxLength = 4;
      this.textBox8.Name = "textBox8";
      this.textBox8.Size = new Size(114, 22);
      this.textBox8.TabIndex = 63;
      this.textBox8.Text = "DEDUCTION   ";
      this.textBox8.TextAlign = HorizontalAlignment.Right;
      this.textBox7.Anchor = AnchorStyles.None;
      this.textBox7.BackColor = Color.AliceBlue;
      this.textBox7.BorderStyle = BorderStyle.None;
      this.textBox7.CharacterCasing = CharacterCasing.Upper;
      this.textBox7.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox7.ForeColor = Color.DarkBlue;
      this.textBox7.Location = new Point(27, 234);
      this.textBox7.MaxLength = 4;
      this.textBox7.Name = "textBox7";
      this.textBox7.Size = new Size(114, 22);
      this.textBox7.TabIndex = 62;
      this.textBox7.Text = "NET WT   ";
      this.textBox7.TextAlign = HorizontalAlignment.Right;
      this.tbxReminder.Anchor = AnchorStyles.None;
      this.tbxReminder.BorderStyle = BorderStyle.FixedSingle;
      this.tbxReminder.CharacterCasing = CharacterCasing.Upper;
      this.tbxReminder.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxReminder.Location = new Point(144, 122);
      this.tbxReminder.MaxLength = 50;
      this.tbxReminder.Name = "tbxReminder";
      this.tbxReminder.ReadOnly = true;
      this.tbxReminder.Size = new Size(145, 29);
      this.tbxReminder.TabIndex = 2;
      this.textBox6.Anchor = AnchorStyles.None;
      this.textBox6.BackColor = Color.AliceBlue;
      this.textBox6.BorderStyle = BorderStyle.None;
      this.textBox6.CharacterCasing = CharacterCasing.Upper;
      this.textBox6.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox6.ForeColor = Color.DarkBlue;
      this.textBox6.Location = new Point(11, 474);
      this.textBox6.MaxLength = 4;
      this.textBox6.Name = "textBox6";
      this.textBox6.Size = new Size(114, 22);
      this.textBox6.TabIndex = 61;
      this.textBox6.Text = "PAID";
      this.textBox6.TextAlign = HorizontalAlignment.Right;
      this.tbxOldBillNumber.Anchor = AnchorStyles.None;
      this.tbxOldBillNumber.BorderStyle = BorderStyle.FixedSingle;
      this.tbxOldBillNumber.CharacterCasing = CharacterCasing.Upper;
      this.tbxOldBillNumber.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxOldBillNumber.Location = new Point(145, 86);
      this.tbxOldBillNumber.MaxLength = 6;
      this.tbxOldBillNumber.Name = "tbxOldBillNumber";
      this.tbxOldBillNumber.ReadOnly = true;
      this.tbxOldBillNumber.Size = new Size(144, 29);
      this.tbxOldBillNumber.TabIndex = 1;
      this.tbxOldBillNumber.TextAlign = HorizontalAlignment.Right;
      this.tbxDeductions.Anchor = AnchorStyles.None;
      this.tbxDeductions.BorderStyle = BorderStyle.FixedSingle;
      this.tbxDeductions.CharacterCasing = CharacterCasing.Upper;
      this.tbxDeductions.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxDeductions.Location = new Point(145, 193);
      this.tbxDeductions.MaxLength = 5;
      this.tbxDeductions.Name = "tbxDeductions";
      this.tbxDeductions.ReadOnly = true;
      this.tbxDeductions.Size = new Size(143, 29);
      this.tbxDeductions.TabIndex = 4;
      this.tbxDeductions.Text = "0";
      this.tbxDeductions.TextAlign = HorizontalAlignment.Right;
      this.textBox5.Anchor = AnchorStyles.None;
      this.textBox5.BackColor = Color.AliceBlue;
      this.textBox5.BorderStyle = BorderStyle.None;
      this.textBox5.CharacterCasing = CharacterCasing.Upper;
      this.textBox5.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox5.ForeColor = Color.DarkBlue;
      this.textBox5.Location = new Point(27, 439);
      this.textBox5.MaxLength = 4;
      this.textBox5.Name = "textBox5";
      this.textBox5.Size = new Size(114, 22);
      this.textBox5.TabIndex = 60;
      this.textBox5.Text = "INTEREST   ";
      this.textBox5.TextAlign = HorizontalAlignment.Right;
      this.cbType.Anchor = AnchorStyles.None;
      this.cbType.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.cbType.ForeColor = Color.Gold;
      this.cbType.FormattingEnabled = true;
      this.cbType.Items.AddRange(new object[3]
      {
        (object) "GOLD",
        (object) "SILVER",
        (object) "OTHERS"
      });
      this.cbType.Location = new Point(145, 46);
      this.cbType.Name = "cbType";
      this.cbType.Size = new Size(144, 32);
      this.cbType.TabIndex = 0;
      this.textBox4.Anchor = AnchorStyles.None;
      this.textBox4.BackColor = Color.AliceBlue;
      this.textBox4.BorderStyle = BorderStyle.None;
      this.textBox4.CharacterCasing = CharacterCasing.Upper;
      this.textBox4.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox4.ForeColor = Color.DarkBlue;
      this.textBox4.Location = new Point(27, 404);
      this.textBox4.MaxLength = 4;
      this.textBox4.Name = "textBox4";
      this.textBox4.Size = new Size(114, 22);
      this.textBox4.TabIndex = 59;
      this.textBox4.Text = "CHIT   ";
      this.textBox4.TextAlign = HorizontalAlignment.Right;
      this.textBox3.Anchor = AnchorStyles.None;
      this.textBox3.BackColor = Color.AliceBlue;
      this.textBox3.BorderStyle = BorderStyle.None;
      this.textBox3.CharacterCasing = CharacterCasing.Upper;
      this.textBox3.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox3.ForeColor = Color.DarkBlue;
      this.textBox3.Location = new Point(27, 370);
      this.textBox3.MaxLength = 4;
      this.textBox3.Name = "textBox3";
      this.textBox3.Size = new Size(114, 22);
      this.textBox3.TabIndex = 58;
      this.textBox3.Text = "ROI    ";
      this.textBox3.TextAlign = HorizontalAlignment.Right;
      this.tbxweight.Anchor = AnchorStyles.None;
      this.tbxweight.BorderStyle = BorderStyle.FixedSingle;
      this.tbxweight.CharacterCasing = CharacterCasing.Upper;
      this.tbxweight.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxweight.Location = new Point(144, 158);
      this.tbxweight.MaxLength = 7;
      this.tbxweight.Name = "tbxweight";
      this.tbxweight.ReadOnly = true;
      this.tbxweight.Size = new Size(144, 29);
      this.tbxweight.TabIndex = 3;
      this.tbxweight.TextAlign = HorizontalAlignment.Right;
      this.textBox2.Anchor = AnchorStyles.None;
      this.textBox2.BackColor = Color.AliceBlue;
      this.textBox2.BorderStyle = BorderStyle.None;
      this.textBox2.CharacterCasing = CharacterCasing.Upper;
      this.textBox2.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox2.ForeColor = Color.DarkBlue;
      this.textBox2.Location = new Point(27, 336);
      this.textBox2.MaxLength = 4;
      this.textBox2.Name = "textBox2";
      this.textBox2.Size = new Size(114, 22);
      this.textBox2.TabIndex = 57;
      this.textBox2.Text = "AMOUNT   ";
      this.textBox2.TextAlign = HorizontalAlignment.Right;
      this.textBox1.Anchor = AnchorStyles.None;
      this.textBox1.BackColor = Color.AliceBlue;
      this.textBox1.BorderStyle = BorderStyle.None;
      this.textBox1.CharacterCasing = CharacterCasing.Upper;
      this.textBox1.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.textBox1.ForeColor = Color.DarkBlue;
      this.textBox1.Location = new Point(27, 299);
      this.textBox1.MaxLength = 4;
      this.textBox1.Name = "textBox1";
      this.textBox1.Size = new Size(114, 22);
      this.textBox1.TabIndex = 56;
      this.textBox1.Text = "VALUE   ";
      this.textBox1.TextAlign = HorizontalAlignment.Right;
      this.tbxPay.Anchor = AnchorStyles.None;
      this.tbxPay.BackColor = SystemColors.ControlLightLight;
      this.tbxPay.BorderStyle = BorderStyle.FixedSingle;
      this.tbxPay.CharacterCasing = CharacterCasing.Upper;
      this.tbxPay.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxPay.ForeColor = SystemColors.ActiveCaptionText;
      this.tbxPay.Location = new Point(144, 471);
      this.tbxPay.MaxLength = 4;
      this.tbxPay.Name = "tbxPay";
      this.tbxPay.Size = new Size(146, 29);
      this.tbxPay.TabIndex = 53;
      this.tbxPay.TextAlign = HorizontalAlignment.Right;
      ((DataGridView) this.dgvArticles).AllowUserToAddRows = false;
      ((DataGridView) this.dgvArticles).AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
      ((DataGridView) this.dgvArticles).BackgroundColor = SystemColors.ButtonHighlight;
      ((DataGridView) this.dgvArticles).BorderStyle = BorderStyle.None;
      ((DataGridView) this.dgvArticles).CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
      gridViewCellStyle1.Alignment = DataGridViewContentAlignment.MiddleCenter;
      gridViewCellStyle1.BackColor = Color.SkyBlue;
      gridViewCellStyle1.Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle1.ForeColor = Color.DarkBlue;
      gridViewCellStyle1.Padding = new Padding(5);
      ((DataGridView) this.dgvArticles).ColumnHeadersDefaultCellStyle = gridViewCellStyle1;
      ((DataGridView) this.dgvArticles).ColumnHeadersHeight = 30;
      ((Control) this.dgvArticles).ContextMenuStrip = this.contextMenuStrip1;
      ((Control) this.dgvArticles).Dock = DockStyle.Fill;
      ((DataGridView) this.dgvArticles).EditMode = DataGridViewEditMode.EditOnEnter;
      ((DataGridView) this.dgvArticles).EnableHeadersVisualStyles = false;
      ((DataGridView) this.dgvArticles).GridColor = Color.LightBlue;
      ((Control) this.dgvArticles).Location = new Point(3, 3);
      ((Control) this.dgvArticles).Name = "dgvArticles";
      gridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
      gridViewCellStyle2.BackColor = SystemColors.Info;
      gridViewCellStyle2.Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle2.ForeColor = SystemColors.WindowText;
      gridViewCellStyle2.SelectionBackColor = SystemColors.Highlight;
      gridViewCellStyle2.SelectionForeColor = SystemColors.HighlightText;
      gridViewCellStyle2.WrapMode = DataGridViewTriState.True;
      ((DataGridView) this.dgvArticles).RowHeadersDefaultCellStyle = gridViewCellStyle2;
      ((DataGridView) this.dgvArticles).RowHeadersVisible = false;
      ((Control) this.dgvArticles).Size = new Size(658, 317);
      ((Control) this.dgvArticles).TabIndex = 0;
      this.contextMenuStrip1.Items.AddRange(new ToolStripItem[1]
      {
        (ToolStripItem) this.deleteToolStripMenuItem
      });
      this.contextMenuStrip1.Name = "contextMenuStrip1";
      this.contextMenuStrip1.Size = new Size(108, 26);
      this.deleteToolStripMenuItem.Name = "deleteToolStripMenuItem";
      this.deleteToolStripMenuItem.Size = new Size(107, 22);
      this.deleteToolStripMenuItem.Text = "Delete";
      this.panel5.Anchor = AnchorStyles.Top | AnchorStyles.Right;
      this.panel5.Controls.Add((Control) this.textBox13);
      this.panel5.Controls.Add((Control) this.tbxPureWeight);
      this.panel5.Controls.Add((Control) this.textBox12);
      this.panel5.Controls.Add((Control) this.textBox11);
      this.panel5.Controls.Add((Control) this.textBox10);
      this.panel5.Controls.Add((Control) this.textBox9);
      this.panel5.Controls.Add((Control) this.textBox8);
      this.panel5.Controls.Add((Control) this.textBox7);
      this.panel5.Controls.Add((Control) this.tbxReminder);
      this.panel5.Controls.Add((Control) this.textBox6);
      this.panel5.Controls.Add((Control) this.tbxOldBillNumber);
      this.panel5.Controls.Add((Control) this.tbxDeductions);
      this.panel5.Controls.Add((Control) this.textBox5);
      this.panel5.Controls.Add((Control) this.cbType);
      this.panel5.Controls.Add((Control) this.textBox4);
      this.panel5.Controls.Add((Control) this.textBox3);
      this.panel5.Controls.Add((Control) this.tbxweight);
      this.panel5.Controls.Add((Control) this.textBox2);
      this.panel5.Controls.Add((Control) this.textBox1);
      this.panel5.Controls.Add((Control) this.tbxPay);
      this.panel5.Controls.Add((Control) this.tbxTotalInterest);
      this.panel5.Controls.Add((Control) this.tbxChit);
      this.panel5.Controls.Add((Control) this.tbxNetWeight);
      this.panel5.Controls.Add((Control) this.tbxInteresRate);
      this.panel5.Controls.Add((Control) this.tbxAmount);
      this.panel5.Controls.Add((Control) this.tbxValue);
      this.panel5.Controls.Add((Control) this.headerPanel2);
      this.panel5.Location = new Point(679, 2);
      this.panel5.Name = "panel5";
      this.panel5.Size = new Size(309, 576);
      this.panel5.TabIndex = 64;
      this.tbxTotalInterest.Anchor = AnchorStyles.None;
      this.tbxTotalInterest.BackColor = SystemColors.ControlLightLight;
      this.tbxTotalInterest.BorderStyle = BorderStyle.FixedSingle;
      this.tbxTotalInterest.CharacterCasing = CharacterCasing.Upper;
      this.tbxTotalInterest.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxTotalInterest.ForeColor = SystemColors.ActiveCaptionText;
      this.tbxTotalInterest.Location = new Point(144, 436);
      this.tbxTotalInterest.MaxLength = 4;
      this.tbxTotalInterest.Name = "tbxTotalInterest";
      this.tbxTotalInterest.Size = new Size(146, 29);
      this.tbxTotalInterest.TabIndex = 55;
      this.tbxTotalInterest.TextAlign = HorizontalAlignment.Right;
      this.tbxChit.Anchor = AnchorStyles.None;
      this.tbxChit.BorderStyle = BorderStyle.FixedSingle;
      this.tbxChit.CharacterCasing = CharacterCasing.Upper;
      this.tbxChit.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxChit.ForeColor = SystemColors.ActiveCaptionText;
      this.tbxChit.Location = new Point(144, 401);
      this.tbxChit.MaxLength = 4;
      this.tbxChit.Name = "tbxChit";
      this.tbxChit.Size = new Size(146, 29);
      this.tbxChit.TabIndex = 9;
      this.tbxChit.TextAlign = HorizontalAlignment.Right;
      this.tbxNetWeight.Anchor = AnchorStyles.None;
      this.tbxNetWeight.BorderStyle = BorderStyle.FixedSingle;
      this.tbxNetWeight.CharacterCasing = CharacterCasing.Upper;
      this.tbxNetWeight.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxNetWeight.Location = new Point(144, 228);
      this.tbxNetWeight.MaxLength = 7;
      this.tbxNetWeight.Name = "tbxNetWeight";
      this.tbxNetWeight.ReadOnly = true;
      this.tbxNetWeight.Size = new Size(145, 29);
      this.tbxNetWeight.TabIndex = 5;
      this.tbxNetWeight.TextAlign = HorizontalAlignment.Right;
      this.tbxInteresRate.Anchor = AnchorStyles.None;
      this.tbxInteresRate.BorderStyle = BorderStyle.FixedSingle;
      this.tbxInteresRate.CharacterCasing = CharacterCasing.Upper;
      this.tbxInteresRate.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxInteresRate.ForeColor = SystemColors.ActiveCaptionText;
      this.tbxInteresRate.Location = new Point(144, 366);
      this.tbxInteresRate.MaxLength = 4;
      this.tbxInteresRate.Name = "tbxInteresRate";
      this.tbxInteresRate.ReadOnly = true;
      this.tbxInteresRate.Size = new Size(146, 29);
      this.tbxInteresRate.TabIndex = 8;
      this.tbxInteresRate.TextAlign = HorizontalAlignment.Right;
      this.tbxAmount.Anchor = AnchorStyles.None;
      this.tbxAmount.BorderStyle = BorderStyle.FixedSingle;
      this.tbxAmount.CharacterCasing = CharacterCasing.Upper;
      this.tbxAmount.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxAmount.ForeColor = SystemColors.ActiveCaptionText;
      this.tbxAmount.Location = new Point(144, 331);
      this.tbxAmount.MaxLength = 10;
      this.tbxAmount.Name = "tbxAmount";
      this.tbxAmount.ReadOnly = true;
      this.tbxAmount.Size = new Size(146, 29);
      this.tbxAmount.TabIndex = 7;
      this.tbxAmount.TextAlign = HorizontalAlignment.Right;
      this.tbxValue.Anchor = AnchorStyles.None;
      this.tbxValue.BorderStyle = BorderStyle.FixedSingle;
      this.tbxValue.CharacterCasing = CharacterCasing.Upper;
      this.tbxValue.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.tbxValue.ForeColor = SystemColors.ActiveCaptionText;
      this.tbxValue.Location = new Point(144, 296);
      this.tbxValue.MaxLength = 10;
      this.tbxValue.Name = "tbxValue";
      this.tbxValue.ReadOnly = true;
      this.tbxValue.Size = new Size(146, 29);
      this.tbxValue.TabIndex = 6;
      this.tbxValue.TextAlign = HorizontalAlignment.Right;
      ((Control) this.headerPanel2).BackColor = Color.PowderBlue;
      this.headerPanel2.BorderColor = SystemColors.HotTrack;
      this.headerPanel2.BorderStyle = BorderStyles.Single;
      this.headerPanel2.CaptionBeginColor = Color.SkyBlue;
      this.headerPanel2.CaptionEndColor = Color.AliceBlue;
      this.headerPanel2.CaptionGradientDirection = LinearGradientMode.Vertical;
      this.headerPanel2.CaptionHeight = 22;
      this.headerPanel2.CaptionPosition = CaptionPositions.Top;
      this.headerPanel2.CaptionText = "LOAN DETAILS";
      this.headerPanel2.CaptionVisible = true;
      ((Control) this.headerPanel2).Dock = DockStyle.Fill;
      ((Control) this.headerPanel2).Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      ((Control) this.headerPanel2).ForeColor = Color.DarkBlue;
      this.headerPanel2.GradientDirection = LinearGradientMode.ForwardDiagonal;
      this.headerPanel2.GradientEnd = Color.Azure;
      this.headerPanel2.GradientStart = Color.AliceBlue;
      ((Control) this.headerPanel2).Location = new Point(0, 0);
      ((Control) this.headerPanel2).Name = "headerPanel2";
      this.headerPanel2.PanelIcon = (Icon) null;
      this.headerPanel2.PanelIconVisible = false;
      ((Control) this.headerPanel2).Size = new Size(309, 576);
      ((Control) this.headerPanel2).TabIndex = 68;
      this.headerPanel2.TextAntialias = true;
      this.tbxAverageNumberOfDaysForRelease.Anchor = AnchorStyles.Left;
      this.tbxAverageNumberOfDaysForRelease.BackColor = Color.AliceBlue;
      this.tbxAverageNumberOfDaysForRelease.BorderStyle = BorderStyle.None;
      this.tbxAverageNumberOfDaysForRelease.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxAverageNumberOfDaysForRelease.Location = new Point(599, 81);
      this.tbxAverageNumberOfDaysForRelease.Name = "tbxAverageNumberOfDaysForRelease";
      this.tbxAverageNumberOfDaysForRelease.ReadOnly = true;
      this.tbxAverageNumberOfDaysForRelease.Size = new Size(57, 15);
      this.tbxAverageNumberOfDaysForRelease.TabIndex = 10;
      this.tbxAverageNumberOfDaysForRelease.TextAlign = HorizontalAlignment.Center;
      this.tbxNumberOfTimesReleaseExceedTwelveMonths.Anchor = AnchorStyles.Left;
      this.tbxNumberOfTimesReleaseExceedTwelveMonths.BackColor = Color.AliceBlue;
      this.tbxNumberOfTimesReleaseExceedTwelveMonths.BorderStyle = BorderStyle.None;
      this.tbxNumberOfTimesReleaseExceedTwelveMonths.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxNumberOfTimesReleaseExceedTwelveMonths.Location = new Point(597, 102);
      this.tbxNumberOfTimesReleaseExceedTwelveMonths.Name = "tbxNumberOfTimesReleaseExceedTwelveMonths";
      this.tbxNumberOfTimesReleaseExceedTwelveMonths.ReadOnly = true;
      this.tbxNumberOfTimesReleaseExceedTwelveMonths.Size = new Size(57, 15);
      this.tbxNumberOfTimesReleaseExceedTwelveMonths.TabIndex = 9;
      this.tbxNumberOfTimesReleaseExceedTwelveMonths.TextAlign = HorizontalAlignment.Center;
      this.tbxCustomerName.Anchor = AnchorStyles.Left;
      this.tbxCustomerName.BorderStyle = BorderStyle.FixedSingle;
      this.tbxCustomerName.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxCustomerName.Location = new Point(243, 26);
      this.tbxCustomerName.Name = "tbxCustomerName";
      this.tbxCustomerName.Size = new Size(295, 22);
      this.tbxCustomerName.TabIndex = 0;
      this.tbxCustomerCode.Anchor = AnchorStyles.Left;
      this.tbxCustomerCode.BackColor = Color.AliceBlue;
      this.tbxCustomerCode.BorderStyle = BorderStyle.None;
      this.tbxCustomerCode.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxCustomerCode.Location = new Point(143, 29);
      this.tbxCustomerCode.Name = "tbxCustomerCode";
      this.tbxCustomerCode.ReadOnly = true;
      this.tbxCustomerCode.Size = new Size(95, 15);
      this.tbxCustomerCode.TabIndex = 8;
      this.tbxCustomerCode.TextAlign = HorizontalAlignment.Center;
      this.tbxPhoneNumber.Anchor = AnchorStyles.Left;
      this.tbxPhoneNumber.BackColor = Color.AliceBlue;
      this.tbxPhoneNumber.BorderStyle = BorderStyle.None;
      this.tbxPhoneNumber.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxPhoneNumber.ForeColor = Color.MidnightBlue;
      this.tbxPhoneNumber.Location = new Point(143, 150);
      this.tbxPhoneNumber.Name = "tbxPhoneNumber";
      this.tbxPhoneNumber.Size = new Size(204, 15);
      this.tbxPhoneNumber.TabIndex = 11;
      this.tbxAddress3.Anchor = AnchorStyles.Left;
      this.tbxAddress3.BackColor = Color.AliceBlue;
      this.tbxAddress3.BorderStyle = BorderStyle.None;
      this.tbxAddress3.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxAddress3.ForeColor = Color.MidnightBlue;
      this.tbxAddress3.Location = new Point(143, 101);
      this.tbxAddress3.Name = "tbxAddress3";
      this.tbxAddress3.Size = new Size(450, 15);
      this.tbxAddress3.TabIndex = 8;
      this.tbxCell.Anchor = AnchorStyles.Left;
      this.tbxCell.BackColor = Color.AliceBlue;
      this.tbxCell.BorderStyle = BorderStyle.None;
      this.tbxCell.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxCell.ForeColor = Color.MidnightBlue;
      this.tbxCell.Location = new Point(353, 149);
      this.tbxCell.Name = "tbxCell";
      this.tbxCell.Size = new Size(239, 15);
      this.tbxCell.TabIndex = 22;
      this.tbxPincode.Anchor = AnchorStyles.Left;
      this.tbxPincode.BackColor = Color.AliceBlue;
      this.tbxPincode.BorderStyle = BorderStyle.None;
      this.tbxPincode.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxPincode.ForeColor = Color.MidnightBlue;
      this.tbxPincode.Location = new Point(352, 125);
      this.tbxPincode.Name = "tbxPincode";
      this.tbxPincode.Size = new Size(240, 15);
      this.tbxPincode.TabIndex = 10;
      this.tbxAddress1.Anchor = AnchorStyles.Left;
      this.tbxAddress1.BackColor = Color.AliceBlue;
      this.tbxAddress1.BorderStyle = BorderStyle.None;
      this.tbxAddress1.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxAddress1.ForeColor = Color.MidnightBlue;
      this.tbxAddress1.Location = new Point(279, 53);
      this.tbxAddress1.Name = "tbxAddress1";
      this.tbxAddress1.Size = new Size(314, 15);
      this.tbxAddress1.TabIndex = 5;
      this.tbxCity.Anchor = AnchorStyles.Left;
      this.tbxCity.BackColor = Color.AliceBlue;
      this.tbxCity.BorderStyle = BorderStyle.None;
      this.tbxCity.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxCity.ForeColor = Color.MidnightBlue;
      this.tbxCity.Location = new Point(143, 125);
      this.tbxCity.Name = "tbxCity";
      this.tbxCity.Size = new Size(204, 15);
      this.tbxCity.TabIndex = 9;
      this.tbxAddress2.Anchor = AnchorStyles.Left;
      this.tbxAddress2.BackColor = Color.AliceBlue;
      this.tbxAddress2.BorderStyle = BorderStyle.None;
      this.tbxAddress2.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxAddress2.ForeColor = Color.MidnightBlue;
      this.tbxAddress2.Location = new Point(143, 76);
      this.tbxAddress2.Name = "tbxAddress2";
      this.tbxAddress2.Size = new Size(450, 15);
      this.tbxAddress2.TabIndex = 6;
      ((Control) this.headerPanel1).BackColor = Color.PowderBlue;
      this.headerPanel1.BorderColor = SystemColors.HotTrack;
      this.headerPanel1.BorderStyle = BorderStyles.Single;
      this.headerPanel1.CaptionBeginColor = Color.SkyBlue;
      this.headerPanel1.CaptionEndColor = Color.Azure;
      this.headerPanel1.CaptionGradientDirection = LinearGradientMode.Vertical;
      this.headerPanel1.CaptionHeight = 22;
      this.headerPanel1.CaptionPosition = CaptionPositions.Top;
      this.headerPanel1.CaptionText = "CUSTOMER DETAILS";
      this.headerPanel1.CaptionVisible = true;
      ((Control) this.headerPanel1).Controls.Add((Control) this.tbxAverageNumberOfDaysForRelease);
      ((Control) this.headerPanel1).Controls.Add((Control) this.tbxNumberOfTimesReleaseExceedTwelveMonths);
      ((Control) this.headerPanel1).Dock = DockStyle.Fill;
      ((Control) this.headerPanel1).Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      ((Control) this.headerPanel1).ForeColor = Color.DarkBlue;
      this.headerPanel1.GradientDirection = LinearGradientMode.ForwardDiagonal;
      this.headerPanel1.GradientEnd = Color.Azure;
      this.headerPanel1.GradientStart = Color.AliceBlue;
      ((Control) this.headerPanel1).Location = new Point(0, 0);
      ((Control) this.headerPanel1).Name = "headerPanel1";
      this.headerPanel1.PanelIcon = (Icon) null;
      this.headerPanel1.PanelIconVisible = false;
      ((Control) this.headerPanel1).Size = new Size(665, 177);
      ((Control) this.headerPanel1).TabIndex = 30;
      this.headerPanel1.TextAntialias = true;
      this.colArticles.HeaderText = "ARTICLES";
      this.colArticles.Name = "colArticles";
      this.colArticles.Resizable = DataGridViewTriState.True;
      this.colArticles.SortMode = DataGridViewColumnSortMode.Automatic;
      ((Control) this.btnEdit).Anchor = AnchorStyles.Left;
      this.btnEdit.BackColor = Color.LightBlue;
      this.btnEdit.FadeOnFocus = true;
      this.btnEdit.ForeColor = Color.MediumBlue;
      this.btnEdit.ForeColorOnFocus = Color.Red;
      this.btnEdit.ForeColorOnLeave = Color.RoyalBlue;
      this.btnEdit.GlowColor = Color.White;
      this.btnEdit.InnerBorderColor = Color.Transparent;
      ((Control) this.btnEdit).Location = new Point(544, 25);
      ((Control) this.btnEdit).Name = "btnEdit";
      this.btnEdit.OuterBorderColor = Color.MediumSlateBlue;
      this.btnEdit.ShineColor = Color.Transparent;
      ((Control) this.btnEdit).Size = new Size(49, 23);
      ((Control) this.btnEdit).TabIndex = 29;
      ((Control) this.btnEdit).Text = "E&dit";
      this.tbxNotes.Anchor = AnchorStyles.Left;
      this.tbxNotes.BorderStyle = BorderStyle.FixedSingle;
      this.tbxNotes.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxNotes.Location = new Point(7, 149);
      this.tbxNotes.Name = "tbxNotes";
      this.tbxNotes.Size = new Size(126, 22);
      this.tbxNotes.TabIndex = 28;
      this.tbxNotes.Visible = false;
      this.panel3.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      this.panel3.Controls.Add((Control) this.btnEdit);
      this.panel3.Controls.Add((Control) this.tbxNotes);
      this.panel3.Controls.Add((Control) this.tbxNumber);
      this.panel3.Controls.Add((Control) this.pictureBox2);
      this.panel3.Controls.Add((Control) this.tbxCustomerName);
      this.panel3.Controls.Add((Control) this.tbxCustomerCode);
      this.panel3.Controls.Add((Control) this.tbxPhoneNumber);
      this.panel3.Controls.Add((Control) this.tbxAddress3);
      this.panel3.Controls.Add((Control) this.tbxCell);
      this.panel3.Controls.Add((Control) this.tbxPincode);
      this.panel3.Controls.Add((Control) this.tbxAddress1);
      this.panel3.Controls.Add((Control) this.tbxCity);
      this.panel3.Controls.Add((Control) this.tbxAddress2);
      this.panel3.Controls.Add((Control) this.headerPanel1);
      this.panel3.Location = new Point(8, 49);
      this.panel3.Name = "panel3";
      this.panel3.Size = new Size(665, 177);
      this.panel3.TabIndex = 62;
      this.tbxNumber.Anchor = AnchorStyles.Left;
      this.tbxNumber.BackColor = Color.AliceBlue;
      this.tbxNumber.BorderStyle = BorderStyle.None;
      this.tbxNumber.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxNumber.ForeColor = Color.MidnightBlue;
      this.tbxNumber.Location = new Point(143, 53);
      this.tbxNumber.Name = "tbxNumber";
      this.tbxNumber.Size = new Size(130, 15);
      this.tbxNumber.TabIndex = 27;
      this.pictureBox2.Anchor = AnchorStyles.Left;
      this.pictureBox2.Location = new Point(7, 24);
      this.pictureBox2.Name = "pictureBox2";
      this.pictureBox2.Size = new Size(126, 146);
      this.pictureBox2.SizeMode = PictureBoxSizeMode.StretchImage;
      this.pictureBox2.TabIndex = 3;
      this.pictureBox2.TabStop = false;
      this.contextMenuStrip2.Items.AddRange(new ToolStripItem[3]
      {
        (ToolStripItem) this.exportToExcelToolStripMenuItem,
        (ToolStripItem) this.wrapToolStripMenuItem,
        (ToolStripItem) this.viewFullScreenToolStripMenuItem
      });
      this.contextMenuStrip2.Name = "contextMenuStrip1";
      this.contextMenuStrip2.Size = new Size(158, 70);
      this.exportToExcelToolStripMenuItem.Name = "exportToExcelToolStripMenuItem";
      this.exportToExcelToolStripMenuItem.Size = new Size(157, 22);
      this.exportToExcelToolStripMenuItem.Text = "Export to Excel";
      this.wrapToolStripMenuItem.Name = "wrapToolStripMenuItem";
      this.wrapToolStripMenuItem.Size = new Size(157, 22);
      this.wrapToolStripMenuItem.Text = "Wrap";
      this.viewFullScreenToolStripMenuItem.Name = "viewFullScreenToolStripMenuItem";
      this.viewFullScreenToolStripMenuItem.Size = new Size(157, 22);
      this.viewFullScreenToolStripMenuItem.Text = "View full Screen";
      this.panel1.Anchor = AnchorStyles.Left | AnchorStyles.Right;
      this.panel1.BorderStyle = BorderStyle.FixedSingle;
      this.panel1.Controls.Add((Control) this.headerPanel6);
      this.panel1.Controls.Add((Control) this.headerPanel5);
      this.panel1.Controls.Add((Control) this.headerPanel7);
      this.panel1.Controls.Add((Control) this.headerPanel3);
      this.panel1.Controls.Add((Control) this.panel5);
      this.panel1.Controls.Add((Control) this.panel3);
      this.panel1.Location = new Point(5, 7);
      this.panel1.Name = "panel1";
      this.panel1.Size = new Size(999, 661);
      this.panel1.TabIndex = 57;
      ((Control) this.headerPanel6).Anchor = AnchorStyles.Top | AnchorStyles.Right;
      ((Control) this.headerPanel6).BackColor = Color.PowderBlue;
      ((Control) this.headerPanel6).BackgroundImage = (Image) Resources.background_gradient_blue1;
      ((Control) this.headerPanel6).BackgroundImageLayout = ImageLayout.Stretch;
      this.headerPanel6.BorderColor = SystemColors.HotTrack;
      this.headerPanel6.BorderStyle = BorderStyles.Single;
      this.headerPanel6.CaptionBeginColor = Color.PowderBlue;
      this.headerPanel6.CaptionEndColor = Color.AliceBlue;
      this.headerPanel6.CaptionGradientDirection = LinearGradientMode.Vertical;
      this.headerPanel6.CaptionHeight = 22;
      this.headerPanel6.CaptionPosition = CaptionPositions.Top;
      this.headerPanel6.CaptionText = "BILL DATE";
      this.headerPanel6.CaptionVisible = true;
      ((Control) this.headerPanel6).Controls.Add((Control) this.glassButton3);
      ((Control) this.headerPanel6).Controls.Add((Control) this.glassButton4);
      ((Control) this.headerPanel6).Controls.Add((Control) this.tbxBillDate);
      ((Control) this.headerPanel6).Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      ((Control) this.headerPanel6).ForeColor = Color.DarkBlue;
      this.headerPanel6.GradientDirection = LinearGradientMode.Vertical;
      this.headerPanel6.GradientEnd = SystemColors.ControlLight;
      this.headerPanel6.GradientStart = SystemColors.ControlLightLight;
      ((Control) this.headerPanel6).Location = new Point(512, 1);
      ((Control) this.headerPanel6).Name = "headerPanel6";
      this.headerPanel6.PanelIcon = (Icon) null;
      this.headerPanel6.PanelIconVisible = false;
      ((Control) this.headerPanel6).Size = new Size(161, 47);
      ((Control) this.headerPanel6).TabIndex = 80;
      this.headerPanel6.TextAntialias = true;
      ((Control) this.glassButton3).Anchor = AnchorStyles.Top | AnchorStyles.Right;
      this.glassButton3.BackColor = Color.LightBlue;
      this.glassButton3.FadeOnFocus = true;
      ((Control) this.glassButton3).Font = new Font("Comic Sans MS", 15.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.glassButton3.ForeColor = Color.MediumBlue;
      this.glassButton3.ForeColorOnFocus = Color.Red;
      this.glassButton3.ForeColorOnLeave = Color.RoyalBlue;
      this.glassButton3.GlowColor = Color.White;
      ((ButtonBase) this.glassButton3).ImageAlign = ContentAlignment.TopLeft;
      this.glassButton3.InnerBorderColor = Color.Transparent;
      ((Control) this.glassButton3).Location = new Point(-148, 513);
      ((Control) this.glassButton3).Name = "glassButton3";
      this.glassButton3.OuterBorderColor = Color.MediumSlateBlue;
      this.glassButton3.ShineColor = Color.Transparent;
      ((Control) this.glassButton3).Size = new Size(128, 35);
      ((Control) this.glassButton3).TabIndex = 0;
      ((Control) this.glassButton3).Text = "&SAVE";
      ((ButtonBase) this.glassButton3).TextImageRelation = TextImageRelation.ImageBeforeText;
      ((Control) this.glassButton4).Anchor = AnchorStyles.Top | AnchorStyles.Right;
      this.glassButton4.BackColor = Color.LightBlue;
      this.glassButton4.FadeOnFocus = true;
      ((Control) this.glassButton4).Font = new Font("Comic Sans MS", 15.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.glassButton4.ForeColor = Color.MediumBlue;
      this.glassButton4.ForeColorOnFocus = Color.Red;
      this.glassButton4.ForeColorOnLeave = Color.RoyalBlue;
      this.glassButton4.GlowColor = Color.White;
      this.glassButton4.InnerBorderColor = Color.Transparent;
      ((Control) this.glassButton4).Location = new Point(-14, 512);
      ((Control) this.glassButton4).Name = "glassButton4";
      this.glassButton4.OuterBorderColor = Color.MediumSlateBlue;
      this.glassButton4.ShineColor = Color.Transparent;
      ((Control) this.glassButton4).Size = new Size(123, 37);
      ((Control) this.glassButton4).TabIndex = 1;
      ((Control) this.glassButton4).Text = "&EXIT";
      ((ButtonBase) this.glassButton4).TextImageRelation = TextImageRelation.ImageBeforeText;
      this.tbxBillDate.BackColor = Color.AliceBlue;
      this.tbxBillDate.BorderStyle = BorderStyle.None;
      this.tbxBillDate.Dock = DockStyle.Fill;
      this.tbxBillDate.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxBillDate.Location = new Point(0, 0);
      this.tbxBillDate.MaxLength = 10;
      this.tbxBillDate.Name = "tbxBillDate";
      this.tbxBillDate.Size = new Size(159, 22);
      this.tbxBillDate.TabIndex = 1;
      this.tbxBillDate.TextAlign = HorizontalAlignment.Center;
      ((Control) this.headerPanel5).BackColor = Color.PowderBlue;
      ((Control) this.headerPanel5).BackgroundImage = (Image) Resources.background_gradient_blue1;
      ((Control) this.headerPanel5).BackgroundImageLayout = ImageLayout.Stretch;
      this.headerPanel5.BorderColor = SystemColors.HotTrack;
      this.headerPanel5.BorderStyle = BorderStyles.Single;
      this.headerPanel5.CaptionBeginColor = Color.PowderBlue;
      this.headerPanel5.CaptionEndColor = Color.AliceBlue;
      this.headerPanel5.CaptionGradientDirection = LinearGradientMode.Vertical;
      this.headerPanel5.CaptionHeight = 22;
      this.headerPanel5.CaptionPosition = CaptionPositions.Top;
      this.headerPanel5.CaptionText = "BILL NUMBER";
      this.headerPanel5.CaptionVisible = true;
      ((Control) this.headerPanel5).Controls.Add((Control) this.glassButton1);
      ((Control) this.headerPanel5).Controls.Add((Control) this.glassButton2);
      ((Control) this.headerPanel5).Controls.Add((Control) this.tbxBillNumber);
      ((Control) this.headerPanel5).Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      ((Control) this.headerPanel5).ForeColor = Color.DarkBlue;
      this.headerPanel5.GradientDirection = LinearGradientMode.Vertical;
      this.headerPanel5.GradientEnd = SystemColors.ControlLight;
      this.headerPanel5.GradientStart = SystemColors.ControlLightLight;
      ((Control) this.headerPanel5).Location = new Point(8, 1);
      ((Control) this.headerPanel5).Name = "headerPanel5";
      this.headerPanel5.PanelIcon = (Icon) null;
      this.headerPanel5.PanelIconVisible = false;
      ((Control) this.headerPanel5).Size = new Size(161, 47);
      ((Control) this.headerPanel5).TabIndex = 79;
      this.headerPanel5.TextAntialias = true;
      ((Control) this.glassButton1).Anchor = AnchorStyles.Top | AnchorStyles.Right;
      this.glassButton1.BackColor = Color.LightBlue;
      this.glassButton1.FadeOnFocus = true;
      ((Control) this.glassButton1).Font = new Font("Comic Sans MS", 15.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.glassButton1.ForeColor = Color.MediumBlue;
      this.glassButton1.ForeColorOnFocus = Color.Red;
      this.glassButton1.ForeColorOnLeave = Color.RoyalBlue;
      this.glassButton1.GlowColor = Color.White;
      ((ButtonBase) this.glassButton1).ImageAlign = ContentAlignment.TopLeft;
      this.glassButton1.InnerBorderColor = Color.Transparent;
      ((Control) this.glassButton1).Location = new Point(-146, 513);
      ((Control) this.glassButton1).Name = "glassButton1";
      this.glassButton1.OuterBorderColor = Color.MediumSlateBlue;
      this.glassButton1.ShineColor = Color.Transparent;
      ((Control) this.glassButton1).Size = new Size(128, 35);
      ((Control) this.glassButton1).TabIndex = 0;
      ((Control) this.glassButton1).Text = "&SAVE";
      ((ButtonBase) this.glassButton1).TextImageRelation = TextImageRelation.ImageBeforeText;
      ((Control) this.glassButton2).Anchor = AnchorStyles.Top | AnchorStyles.Right;
      this.glassButton2.BackColor = Color.LightBlue;
      this.glassButton2.FadeOnFocus = true;
      ((Control) this.glassButton2).Font = new Font("Comic Sans MS", 15.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.glassButton2.ForeColor = Color.MediumBlue;
      this.glassButton2.ForeColorOnFocus = Color.Red;
      this.glassButton2.ForeColorOnLeave = Color.RoyalBlue;
      this.glassButton2.GlowColor = Color.White;
      this.glassButton2.InnerBorderColor = Color.Transparent;
      ((Control) this.glassButton2).Location = new Point(-12, 512);
      ((Control) this.glassButton2).Name = "glassButton2";
      this.glassButton2.OuterBorderColor = Color.MediumSlateBlue;
      this.glassButton2.ShineColor = Color.Transparent;
      ((Control) this.glassButton2).Size = new Size(123, 37);
      ((Control) this.glassButton2).TabIndex = 1;
      ((Control) this.glassButton2).Text = "&EXIT";
      ((ButtonBase) this.glassButton2).TextImageRelation = TextImageRelation.ImageBeforeText;
      this.tbxBillNumber.BackColor = Color.AliceBlue;
      this.tbxBillNumber.BorderStyle = BorderStyle.None;
      this.tbxBillNumber.Dock = DockStyle.Fill;
      this.tbxBillNumber.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.tbxBillNumber.Location = new Point(0, 0);
      this.tbxBillNumber.Name = "tbxBillNumber";
      this.tbxBillNumber.Size = new Size(159, 22);
      this.tbxBillNumber.TabIndex = 79;
      this.tbxBillNumber.TextAlign = HorizontalAlignment.Center;
      ((Control) this.headerPanel7).Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      ((Control) this.headerPanel7).BackColor = Color.PowderBlue;
      ((Control) this.headerPanel7).BackgroundImage = (Image) Resources.background_gradient_blue1;
      ((Control) this.headerPanel7).BackgroundImageLayout = ImageLayout.Stretch;
      this.headerPanel7.BorderColor = SystemColors.HotTrack;
      this.headerPanel7.BorderStyle = BorderStyles.Single;
      this.headerPanel7.CaptionBeginColor = Color.PowderBlue;
      this.headerPanel7.CaptionEndColor = Color.AliceBlue;
      this.headerPanel7.CaptionGradientDirection = LinearGradientMode.Vertical;
      this.headerPanel7.CaptionHeight = 22;
      this.headerPanel7.CaptionPosition = CaptionPositions.Top;
      this.headerPanel7.CaptionText = "LICENSE";
      this.headerPanel7.CaptionVisible = true;
      ((Control) this.headerPanel7).Controls.Add((Control) this.cbShopCodes);
      ((Control) this.headerPanel7).Controls.Add((Control) this.glassButton8);
      ((Control) this.headerPanel7).Controls.Add((Control) this.glassButton9);
      ((Control) this.headerPanel7).Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      ((Control) this.headerPanel7).ForeColor = Color.DarkBlue;
      this.headerPanel7.GradientDirection = LinearGradientMode.Vertical;
      this.headerPanel7.GradientEnd = SystemColors.ControlLight;
      this.headerPanel7.GradientStart = SystemColors.ControlLightLight;
      ((Control) this.headerPanel7).Location = new Point(173, 1);
      ((Control) this.headerPanel7).Name = "headerPanel7";
      this.headerPanel7.PanelIcon = (Icon) null;
      this.headerPanel7.PanelIconVisible = false;
      ((Control) this.headerPanel7).Size = new Size(335, 47);
      ((Control) this.headerPanel7).TabIndex = 78;
      this.headerPanel7.TextAntialias = true;
      this.cbShopCodes.BackColor = Color.AliceBlue;
      this.cbShopCodes.Dock = DockStyle.Fill;
      this.cbShopCodes.DropDownWidth = 600;
      this.cbShopCodes.FormattingEnabled = true;
      this.cbShopCodes.Location = new Point(0, 0);
      this.cbShopCodes.Name = "cbShopCodes";
      this.cbShopCodes.Size = new Size(333, 23);
      this.cbShopCodes.TabIndex = 24;
      ((Control) this.glassButton8).Anchor = AnchorStyles.Top | AnchorStyles.Right;
      this.glassButton8.BackColor = Color.LightBlue;
      this.glassButton8.FadeOnFocus = true;
      ((Control) this.glassButton8).Font = new Font("Comic Sans MS", 15.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.glassButton8.ForeColor = Color.MediumBlue;
      this.glassButton8.ForeColorOnFocus = Color.Red;
      this.glassButton8.ForeColorOnLeave = Color.RoyalBlue;
      this.glassButton8.GlowColor = Color.White;
      ((ButtonBase) this.glassButton8).ImageAlign = ContentAlignment.TopLeft;
      this.glassButton8.InnerBorderColor = Color.Transparent;
      ((Control) this.glassButton8).Location = new Point(30, 513);
      ((Control) this.glassButton8).Name = "glassButton8";
      this.glassButton8.OuterBorderColor = Color.MediumSlateBlue;
      this.glassButton8.ShineColor = Color.Transparent;
      ((Control) this.glassButton8).Size = new Size(128, 35);
      ((Control) this.glassButton8).TabIndex = 0;
      ((Control) this.glassButton8).Text = "&SAVE";
      ((ButtonBase) this.glassButton8).TextImageRelation = TextImageRelation.ImageBeforeText;
      ((Control) this.glassButton9).Anchor = AnchorStyles.Top | AnchorStyles.Right;
      this.glassButton9.BackColor = Color.LightBlue;
      this.glassButton9.FadeOnFocus = true;
      ((Control) this.glassButton9).Font = new Font("Comic Sans MS", 15.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.glassButton9.ForeColor = Color.MediumBlue;
      this.glassButton9.ForeColorOnFocus = Color.Red;
      this.glassButton9.ForeColorOnLeave = Color.RoyalBlue;
      this.glassButton9.GlowColor = Color.White;
      this.glassButton9.InnerBorderColor = Color.Transparent;
      ((Control) this.glassButton9).Location = new Point(164, 512);
      ((Control) this.glassButton9).Name = "glassButton9";
      this.glassButton9.OuterBorderColor = Color.MediumSlateBlue;
      this.glassButton9.ShineColor = Color.Transparent;
      ((Control) this.glassButton9).Size = new Size(123, 37);
      ((Control) this.glassButton9).TabIndex = 1;
      ((Control) this.glassButton9).Text = "&EXIT";
      ((ButtonBase) this.glassButton9).TextImageRelation = TextImageRelation.ImageBeforeText;
      ((Control) this.headerPanel3).Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
      ((Control) this.headerPanel3).BackColor = Color.AliceBlue;
      this.headerPanel3.BorderColor = SystemColors.HotTrack;
      this.headerPanel3.BorderStyle = BorderStyles.Single;
      this.headerPanel3.CaptionBeginColor = Color.Azure;
      this.headerPanel3.CaptionEndColor = Color.SkyBlue;
      this.headerPanel3.CaptionGradientDirection = LinearGradientMode.ForwardDiagonal;
      this.headerPanel3.CaptionHeight = 22;
      this.headerPanel3.CaptionPosition = CaptionPositions.Top;
      this.headerPanel3.CaptionText = "DETAILED DESCRIPTION OF THE ARTICLES";
      this.headerPanel3.CaptionVisible = true;
      ((Control) this.headerPanel3).Controls.Add((Control) this.tableLayoutPanel2);
      ((Control) this.headerPanel3).Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      ((Control) this.headerPanel3).ForeColor = Color.DarkBlue;
      this.headerPanel3.GradientDirection = LinearGradientMode.ForwardDiagonal;
      this.headerPanel3.GradientEnd = Color.Azure;
      this.headerPanel3.GradientStart = Color.AliceBlue;
      ((Control) this.headerPanel3).Location = new Point(8, 231);
      ((Control) this.headerPanel3).Name = "headerPanel3";
      this.headerPanel3.PanelIcon = (Icon) null;
      this.headerPanel3.PanelIconVisible = false;
      ((Control) this.headerPanel3).Size = new Size(665, 347);
      ((Control) this.headerPanel3).TabIndex = 58;
      this.headerPanel3.TextAntialias = true;
      this.tableLayoutPanel2.ColumnCount = 1;
      this.tableLayoutPanel2.ColumnStyles.Add(new ColumnStyle());
      this.tableLayoutPanel2.Controls.Add((Control) this.dgvArticles, 0, 0);
      this.tableLayoutPanel2.Dock = DockStyle.Fill;
      this.tableLayoutPanel2.Location = new Point(0, 0);
      this.tableLayoutPanel2.Name = "tableLayoutPanel2";
      this.tableLayoutPanel2.RowCount = 1;
      this.tableLayoutPanel2.RowStyles.Add(new RowStyle());
      this.tableLayoutPanel2.Size = new Size(663, 323);
      this.tableLayoutPanel2.TabIndex = 66;
      this.timer1.Enabled = true;
      this.timer1.Interval = 500;
      this.colPureWeight.HeaderText = "PUREWEIGHT";
      this.colPureWeight.Name = "colPureWeight";
      this.colHiddenRemarks.HeaderText = "HIDDENREMARKS";
      this.colHiddenRemarks.Name = "colHiddenRemarks";
      this.colPurity.HeaderText = "%";
      this.colPurity.Name = "colPurity";
      this.colNetWeight.HeaderText = "NETWEIGHT";
      this.colNetWeight.Name = "colNetWeight";
      this.colDeduction.HeaderText = "DEDUCTION";
      this.colDeduction.Name = "colDeduction";
      this.colGrossWeight.HeaderText = "GROSS WEIGHT";
      this.colGrossWeight.Name = "colGrossWeight";
      this.colNo.FillWeight = 20f;
      this.colNo.HeaderText = "NO";
      this.colNo.Name = "colNo";
      this.colArticlesDetails.FillWeight = 60f;
      this.colArticlesDetails.HeaderText = "DESCRIPTION";
      this.colArticlesDetails.Name = "colArticlesDetails";
      this.colArticlesDetails.Resizable = DataGridViewTriState.True;
      this.colArticlesDetails.SortMode = DataGridViewColumnSortMode.NotSortable;
      this.AutoScaleDimensions = new SizeF(96f, 96f);
      this.AutoScaleMode = AutoScaleMode.Dpi;
      this.ClientSize = new Size(1008, 632);
      this.Controls.Add((Control) this.panel1);
      this.FormBorderStyle = FormBorderStyle.None;
      this.Name = nameof (FormPledgeBill);
      this.Text = nameof (FormPledgeBill);
      this.Load += new EventHandler(this.FormPledgeBill_Load);
      ((ISupportInitialize) this.dgvArticles).EndInit();
      this.contextMenuStrip1.ResumeLayout(false);
      this.panel5.ResumeLayout(false);
      this.panel5.PerformLayout();
      ((Control) this.headerPanel1).ResumeLayout(false);
      ((Control) this.headerPanel1).PerformLayout();
      this.panel3.ResumeLayout(false);
      this.panel3.PerformLayout();
      ((ISupportInitialize) this.pictureBox2).EndInit();
      this.contextMenuStrip2.ResumeLayout(false);
      this.panel1.ResumeLayout(false);
      ((Control) this.headerPanel6).ResumeLayout(false);
      ((Control) this.headerPanel6).PerformLayout();
      ((Control) this.headerPanel5).ResumeLayout(false);
      ((Control) this.headerPanel5).PerformLayout();
      ((Control) this.headerPanel7).ResumeLayout(false);
      ((Control) this.headerPanel3).ResumeLayout(false);
      this.tableLayoutPanel2.ResumeLayout(false);
      this.ResumeLayout(false);
    }
  }
}
